### ISSUE TITLE
Unable to download video from youtube

### ISSUE THREAD

**Issue by alokfuterox** [jerome-amp/youtube#1]
Unable to download this video 
https://www.youtube.com/watch?v=ReXw6TOnUOc

Please have a look on this url

**Comment by jerome-amp** [comment]
Indeed youtube changed the script of his JS player, downloading videos protected by the signature system was no longer working. This has been corrected, can you confirm ?
Thanks for your report ;)

**Comment by alokfuterox** [comment]
Yes
Correct.
Decoding signature not working.  Getting ha error function cr not fount.

Sent from my iPhone

On 08-Dec-2015, at 10:55 pm, jerome-amp <notifications@github.com> wrote:

Indeed youtube changed the script of his JS player, downloading videos
protected by the signature system was no longer working. This has been
corrected, can you confirm ?
Thanks for your report ;)

—
Reply to this email directly or view it on GitHub
<https://github.com/jerome-amp/youtube/issues/1#issuecomment-162952497>.

**Comment by alokfuterox** [comment]
Hi, 
Still not able to download the video file.

Regards
Alok

**Comment by alokfuterox** [comment]
Not getting real content form youtube page using 
file_get_contents();

Regards
Alok

**Comment by jerome-amp** [comment]
What is the version of your PHP ? If it is less than 5.6 then the parameter "verify_peer_name" of the file_get_contents context of is not supported.

**Comment by alokfuterox** [comment]
my php version is 5.3

**Comment by jerome-amp** [comment]
I delete the "verify_peer_name" parameter, and commit changes.
